language: node_js
node_js:
- 6
- 8
- 10
cache:
  directories:
  - node_modules
script:
- npm run lint
- npm run test
- npm run build
jobs:
  include:
  - stage: npm release
    if: tag IS present
    node_js: '10'
    script: echo "Publishing to npm..."
    deploy:
      provider: npm
      skip_cleanup: true
      on:
        tags: true
      email: npm@nerdwallet.com
      api_key:
        secure: JVuSXxqx4BzQpcKur6qHOu+yMB69M2nBFhPQfeXSHhbG5kni8pw5A1t0QXirX8hs/2y0vAcpSa7wKdoOoR2y5B58rFo3UnaxsFclvpoNIYu3twMTiRl1GZrCziawRTsYp+SnPuXZzbUV62Gd/g0S4IOMLldZKiPncoAMJiX53bcIJRoJOh10cGCfrsqka3m7NyxrrKk+87fn9swqkTK5oKO9kvdaGb5U/pxeNV+ai4kZuV3q41CTHkkbCq4JZ6zoWQTRqvsFhPAZ4GaO33dDK7XmSmaV4oMpDkb9A0DagO6KUW2wai+/k9GkuXfriE3u1FW3sNjDGzXD6n6257gJY33HzKBuZmDLZTEV6IPy6/VVgt28/ACSSoL+hfRWATgzXMb2dzs2ol/1v6ZOiqV0WVfzJwqR3Q+m55jE8s5f9yCaEmfn9IdF84TrseYnbzpTAX4YG2Cb2t+wQVqhfipcQiEAwZvE1SAqtsWRT0+Wvsww3j6sTqZL5L2F8Jlo4mM+vAlNGbhNWF2PHeA0ftpCZnYy1vTINrh3FhJx2+l1Y/OIQLu4tO4aBJhzJcVcCDPTdHnMKTlafKHRmEiRaXPoW8lbHMXoj50OCyK7Zeg0+iGX/ONpWQsywtF+V9osJxRRP6jHaWuAemGrGpSeWN0gTykf2texu+P3jHaloDmF6DU=
