language: node_js
node_js:
- 6
- 8
- 10
cache:
  directories:
  - node_modules
script:
- npm run lint
- npm run test
- npm run build
jobs:
  include:
  - stage: npm release
    if: tag IS present
    node_js: '10'
    script: echo "Publishing to npm..."
    deploy:
      provider: npm
      skip_cleanup: true
      on:
        tags: true
      email: npm@nerdwallet.com
      api_key:
        secure: Lv35HSGcorEuExj3cRVhpp5K7Uh0qHIZHH2zwTybYrthZM2ccRo8McX2G5yqOkJXrcjsFDstyy6FYD26sADt/EB3Th2Yw/a+TJ79w14Df3iFCk+Ij8ktAI8y2kW2U6vFhG2ZvKetSgRwFRkW9fxfnttT/fXA8DUeeQ2Q8f7+n2JlXiuhRdAuFSq+QJbA36jzrq43zfYBzt7a5PI29MuRwrkd99xMfIMAepd3xXfcSaqjjne420SL/dUZrxvUtsJCBFWK0vb2X12M98uOJ2QZcNghqITx3A9eFPoAS/P4+r4mp0k7ZQsXM/d4qlQSZGAaXQUvPwIJNf2fJjiTXcyBsry3Uwgrs1+Ly2sDxLh/RbhAzAckFMsJvESkxFtGRnfHozdn6QThDVYtCduAZCD/LM5/ohQhvVtlyNtvC5OHC+w2wHdxo81pb8htIgEXRzdT3TgoSJjVvjwQ82czHegX+Rho51cSO4wSHWlFn6aSWSuE+69TR+22WzVkTGghmYKXMCh1HIisNuvCTsSWl+ln89ae14Bdunc/rGy2xE6wF58/JaO7DJWFjGn/W507HM7J9icnWKXkjsohGqLY8ESaPPiVqS5J/nYRWBWScHRDVO1WPFIwvQ5dFBNbxOz0kQumbo8EJV2SN9FufXy9Z7hV7/2cBvm8pjyHR5O8elzxRSM=
